import streamlit as st
import pandas as pd
from fpdf import FPDF
from datetime import date
import os

# ==========================================
# إعدادات الصفحة
# ==========================================
st.set_page_config(page_title="Shekto Merchant OS", layout="centered", page_icon="⚖️")

st.markdown("""
    <style>
    .big-font { font-size:22px !important; font-weight: bold; color: #0D47A1; background-color: #E3F2FD; padding: 10px; border-radius: 5px;}
    .loss-font { font-size:18px !important; font-weight: bold; color: #B71C1C; background-color: #FFEBEE; padding: 10px; border-radius: 5px;}
    .profit-font { font-size:18px !important; font-weight: bold; color: #1B5E20; background-color: #E8F5E9; padding: 10px; border-radius: 5px;}
    </style>
""", unsafe_allow_html=True)

# ==========================================
# دالة توليد تقرير الـ PDF 
# ==========================================
class AssayPDF(FPDF):
    def footer(self):
        self.set_y(-40)
        self.set_font("Arial", 'B', 10)
        
        # تواقيع الاعتماد
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
        self.cell(60, 10, "Shekto Manager", align='C')
        self.cell(70, 10, "Lab Engineer", align='C')
        self.cell(60, 10, "Official Representative", align='C')
        
        self.ln(15)
        self.set_font("Arial", 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, "Generated by Shekto Merchant OS - Profit Engineering Systems", align='C')

def generate_assay_certificate(bar_id, source_project, rep_name, gross_weight, my_sheshena, equiv_weight_21k, equiv_weight_24k, global_oz_usd, usd_to_sdg, aed_to_sdg, fair_total_value_sdg, fair_total_value_aed):
    pdf = AssayPDF()
    pdf.add_page()
    
    # اللوغو والترويسة
    if os.path.exists("logo.png"):
        pdf.image("logo.png", x=10, y=8, w=30)
    
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(40) 
    pdf.cell(0, 10, "SHEKTO MINING & GOLD", ln=True, align='L')
    pdf.set_font("Arial", '', 11)
    pdf.cell(40)
    pdf.cell(0, 8, "Official Assay & Valuation Certificate", ln=True, align='L')
    
    pdf.ln(5)
    pdf.line(10, 35, 200, 35)
    pdf.ln(10)

    # 1. Document Details
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, " 1. Document Details", ln=True, fill=True)
    pdf.set_font("Arial", '', 10)
    pdf.ln(2)
    pdf.cell(50, 8, f"Date: {date.today()}", ln=False)
    pdf.cell(70, 8, f"Bar ID: {bar_id}", ln=False)
    pdf.cell(0, 8, f"Source/Project: {source_project}", ln=True)
    pdf.cell(0, 8, f"Representative: {rep_name}", ln=True)
    pdf.ln(5)

    # 2. Assay Results
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, " 2. Laboratory Assay Results", ln=True, fill=True)
    pdf.set_font("Arial", '', 10)
    pdf.ln(2)
    pdf.cell(90, 10, "Gross Weight (grams):", border=1)
    pdf.cell(0, 10, f"{gross_weight:.2f} g", border=1, ln=True, align='C')
    
    pdf.cell(90, 10, "Purity / Sheshena (Shares/1000):", border=1)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(0, 10, f"{my_sheshena:.0f}", border=1, ln=True, align='C')
    pdf.set_font("Arial", '', 10)
    
    pdf.cell(90, 10, "Fine Gold Weight (24K - Pure):", border=1)
    pdf.cell(0, 10, f"{equiv_weight_24k:.2f} g", border=1, ln=True, align='C')
    
    pdf.cell(90, 10, "Equivalent Trading Weight (21K):", border=1)
    pdf.cell(0, 10, f"{equiv_weight_21k:.2f} g", border=1, ln=True, align='C')
    pdf.ln(5)

    # 3. Market Valuation
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, " 3. Market Financial Valuation", ln=True, fill=True)
    pdf.set_font("Arial", '', 10)
    pdf.ln(2)
    pdf.cell(90, 10, "Global Gold Price (USD/Oz):", border=1)
    pdf.cell(0, 10, f"${global_oz_usd:,.2f}", border=1, ln=True, align='C')
    
    pdf.cell(90, 10, "Parallel Rate (USD to SDG):", border=1)
    pdf.cell(0, 10, f"{usd_to_sdg:,.0f} SDG", border=1, ln=True, align='C')

    pdf.cell(90, 10, "Parallel Rate (AED to SDG):", border=1)
    pdf.cell(0, 10, f"{aed_to_sdg:,.0f} SDG", border=1, ln=True, align='C')
    
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(200, 255, 200)
    pdf.cell(90, 12, "FAIR TOTAL VALUE (SDG):", border=1, fill=True)
    pdf.cell(0, 12, f"{fair_total_value_sdg:,.0f} SDG", border=1, ln=True, align='C', fill=True)
    
    # إضافة القيمة بالدرهم الإماراتي لأهميتها في الصادر
    pdf.set_fill_color(220, 235, 255) # لون أزرق فاتح
    pdf.cell(90, 12, "FAIR TOTAL VALUE (AED):", border=1, fill=True)
    pdf.cell(0, 12, f"{fair_total_value_aed:,.0f} AED", border=1, ln=True, align='C', fill=True)

    return pdf.output(dest='S').encode('latin-1')

# ==========================================
# واجهة المستخدم (UI)
# ==========================================
st.title("⚖️ Shekto Merchant OS")
st.markdown("**بوابة تجارة الذهب: التسعير، الششنة، وإصدار الشهادات**")
st.divider()

# --- 0. بيانات توثيق السبيكة (للطباعة) ---
st.subheader("📝 0. بيانات توثيق السبيكة (للطباعة)")
c_doc1, c_doc2, c_doc3 = st.columns(3)
with c_doc1:
    bar_id = st.text_input("رقم السبيكة (Bar ID)", "B-2026-001")
with c_doc2:
    source_project = st.text_input("مصدر الذهب (English)", "Blue Nile Project")
with c_doc3:
    rep_name = st.text_input("المندوب / المستلم (English)", "SMRC Representative")
st.divider()

# ==========================================
# 1. محرك التسعير المزدوج (تمت إعادة الدرهم)
# ==========================================
st.subheader("🌍 1. مؤشرات السوق والعملات (اليوم)")
col_oz, col_usd, col_aed = st.columns(3)
with col_oz:
    global_oz_usd = st.number_input("سعر الأونصة العالمي ($)", value=2050.0, step=10.0)
with col_usd:
    usd_to_sdg = st.number_input("سعر الدولار (موازي)", value=2500.0, step=50.0)
with col_aed:
    aed_to_sdg = st.number_input("سعر الدرهم (موازي)", value=680.0, step=10.0)

gram_24k_usd = global_oz_usd / 31.103
gram_21k_usd = gram_24k_usd * 0.875
gram_21k_sdg = gram_21k_usd * usd_to_sdg
gram_24k_sdg = gram_24k_usd * usd_to_sdg

st.markdown(f"<div class='big-font'>السعر العادل لجرام (21): {gram_21k_sdg:,.0f} جنيه سوداني</div>", unsafe_allow_html=True)
st.divider()

# ==========================================
# 2. محرك الشَّشْنَة 
# ==========================================
st.subheader("🔥 2. فك شفرة الشَّشْنَة (المعمل الداخلي)")
c1, c2 = st.columns(2)
with c1:
    gross_weight = st.number_input("الوزن الإجمالي للقطعة (جرام)", value=112.0, step=1.0)
with c2:
    my_sheshena = st.number_input("أسهم الششنة (من 1000)", value=890.0, step=1.0)

equiv_weight_21k = gross_weight * (my_sheshena / 875.0)
equiv_weight_24k = gross_weight * (my_sheshena / 1000.0)

fair_total_value_sdg = equiv_weight_21k * gram_21k_sdg
# حساب القيمة بالدرهم الإماراتي
fair_total_value_aed = fair_total_value_sdg / aed_to_sdg if aed_to_sdg > 0 else 0

c3, c4, c5 = st.columns(3)
c3.metric("الذهب الصافي (24K)", f"{equiv_weight_24k:.2f} g")
c4.metric("الوزن التجاري (21K)", f"{equiv_weight_21k:.2f} g")
c5.metric("القيمة العادلة (درهم)", f"{fair_total_value_aed:,.0f} AED")
st.divider()

# ==========================================
# 3. رادار تلاعب التجار
# ==========================================
st.subheader("🕵️ 3. رادار تلاعب التجار والمعامل الخارجية")
merchant_sheshena = st.number_input("أسهم الششنة من معمل التاجر", value=880.0, step=1.0)

if merchant_sheshena < my_sheshena:
    lost_shares = my_sheshena - merchant_sheshena
    lost_weight_21k = gross_weight * (lost_shares / 875.0)
    financial_loss_sdg = lost_weight_21k * gram_21k_sdg
    financial_loss_usd = financial_loss_sdg / usd_to_sdg if usd_to_sdg > 0 else 0
    st.markdown(f"<div class='loss-font'>🚨 التاجر خفض تقييمك بـ {lost_shares} أسهم.<br>خسارتك: {financial_loss_sdg:,.0f} جنيه (حوالي ${financial_loss_usd:,.0f})</div>", unsafe_allow_html=True)
elif merchant_sheshena == my_sheshena:
    st.success("✅ تطابق تام. المعمل الخارجي نزيه والتسعير دقيق.")
st.divider()

# ==========================================
# 4. اقتصاد الجوال (جدوى الطحن)
# ==========================================
st.subheader("📦 4. الجدوى الاقتصادية (اقتصاد الجوال)")
col_j1, col_j2 = st.columns(2)
with col_j1:
    cost_per_jawal = st.number_input("رسوم الطحن للجوال (جنيه)", value=25000.0, step=1000.0)
with col_j2:
    num_jawals = st.number_input("عدد الجوالات المطحونة", value=100.0, step=10.0)

total_opex_sdg = cost_per_jawal * num_jawals
actual_weight_21k_sold = gross_weight * (merchant_sheshena / 875.0)
actual_revenue_sdg = actual_weight_21k_sold * gram_21k_sdg
net_cash_sdg = actual_revenue_sdg - total_opex_sdg

if net_cash_sdg > 0:
    st.markdown(f"<div class='profit-font'>✅ صافي الربح بعد رسوم الطحن: {net_cash_sdg:,.0f} جنيه</div>", unsafe_allow_html=True)
else:
    st.markdown(f"<div class='loss-font'>🚫 خسارة محققة: {net_cash_sdg:,.0f} جنيه</div>", unsafe_allow_html=True)

st.divider()

# ==========================================
# زر توليد تقرير الـ PDF
# ==========================================
st.subheader("🖨️ طباعة شهادة التقييم الرسمية")
st.info("💡 سيتم استخراج الشهادة باللغة الإنجليزية لتكون وثيقة رسمية معتمدة للتوقيع.")

if st.button("📥 إصدار شهادة التقييم (Generate Certificate)", type="primary"):
    try:
        # تمرير جميع المتغيرات بما فيها aed_to_sdg و fair_total_value_aed
        pdf_bytes = generate_assay_certificate(
            bar_id, source_project, rep_name, gross_weight, my_sheshena, 
            equiv_weight_21k, equiv_weight_24k, global_oz_usd, usd_to_sdg, aed_to_sdg, fair_total_value_sdg, fair_total_value_aed
        )
        st.download_button(
            label="📄 تحميل الشهادة (Download PDF)",
            data=pdf_bytes,
            file_name=f"Assay_Certificate_{bar_id}.pdf",
            mime="application/pdf"
        )
        st.success("✅ تم إصدار الشهادة بنجاح! جاهزة للطباعة والتوقيع.")
    except Exception as e:
        st.error(f"حدث خطأ أثناء توليد الملف: {e}")